# Generated by Django 4.2.2 on 2023-07-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_project_update_project_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects", verbose_name="Imagen"),
        ),
    ]
